name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  ci:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # The official GitHub setup-python action can be faster than installing
      # Python with uv, because GitHub caches the Python versions alongside
      # the runner.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check

      - name: Check types
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest
